# -*- coding: utf-8 -*-
"""00_pytorch_fundamentals_videos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOcD8dnT-b74ebKaFHlGQ64mXagO7Zvp

## 00.pyTorch Fundamentals

Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/
"""

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

"""## Introduction to Tensors

### creating tensors
"""

# scalar
scalar = torch.tensor(7)
scalar

scalar.ndim

#get tensor back as python int
scalar.item()

# Vector

vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

# MATRIX(MATRIX,TENSOR는 대문자로 적어야함. scalar,vector는 소문자)
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

MATRIX.ndim

MATRIX[0]

MATRIX.shape

#tensor(대문자로 적어야)
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
tensor

tensor.ndim

tensor.shape

"""###Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> lokk at data -> update random numbers'
"""

# Create a random tensor of size(3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

random_tensor.ndim

# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # height,width,color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

"""### Zeros and ones"""

# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

zeros*random_tensor

# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

one = torch.ones(3,4)
one

ones.dtype

random_tensor.dtype

"""###Creating a range of tensors and tensors-like"""

# use torch.range() and get deprecated message, use torch,arange()
one_to_ten = torch.arange(start=0,end=10,step=1)
one_to_ten

#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

"""### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors on the right device
"""

#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #what datatype is the tensor(e.g.)
                               device=None,# what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations)
float_32_tensor

float_32_tensor.dtype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

a = float_16_tensor*float_32_tensor
a.dtype

int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)

float_32_tensor*int_32_tensor

"""### Getting information from tensors(tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors on the right device - to get device from a tensor,can use 'tensor.device'
"""

#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

some_tensor.size(), some_tensor.shape

# find out deetails about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

"""
### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

"""

# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

# Multiply tensor by 10
tensor * 10

tensor

# Substract 10
tensor -10

# Try out Pytorch in-built functions
torch.mul(tensor,10)

torch.add(tensor,10)

"""### Matrix multiplication

Two main ways of performing multiplication in nueral networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rules that performing matrix multiplicaion needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work
2. The resulting matirix has the shape of the **outer dimentions**:
* '(2,3) @ (3,2)' -> '(2,2)'
* '(3,2) @ (2,3)' -> '(3,3)'
"""

# Element wise multiplication
print(tensor, "*",tensor)
print(f"Equals: {tensor*tensor}")

# Matrix multiplication
torch.matmul(tensor,tensor)

tensor

# Matrix multiplication by  hand
1*1 + 2*2 + 3*3

tensor @ tensor

# Commented out IPython magic to ensure Python compatibility.
# %%time
# value = 0
# for i in range(len(tensor)):
#   value += tensor[i] *tensor[i]
# print(value)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# torch.matmul(tensor,tensor)

"""### One of the most common errors in deep learning:shape errors"""

#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B)

tensor_A.shape, tensor_B.shape

"""To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor
"""

tensor_B, tensor_B.shape

tensor_B.T, tensor_B.T.shape

torch.matmul(tensor_A,tensor_B.T).shape

# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A ={tensor_A.shape},tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutpur shape: {output.shape}")

"""##Finding the min,max,mean,sum,etc(tensor aggregation)"""

# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

#Find the min
torch.min(x), x.min()

#Find the max
torch.max(x), x.max()

#Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

# Find the sum
torch.sum(x), x.sum()

"""## Finding the positional min and max"""

x

#Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

x[0]

# Find the position in tensor that has the maximum value with argmax()
x.argmax()

x[9]

"""## Reshaping, stacking, sqeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each othe (vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* unsqueeze - add a '1' dimension to a target tensor
* permute - Return a view of the input with dimensions permuted(swapped) in a certain way
"""

# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

# Change the view
z = x.view(1,9)
z, z.shape

#Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

x

# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\n New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

# torch.permute - rearranges thedimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # {height, width,colour_channels}

# permute original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0 ->1, 1->2, 2->0

print(f"Previous sahpe: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

"""## Indexing (selecting data from tensors)

Indexing with Pythorch is similar to indexing with Numpy
"""

# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

# Let's index on our new tensor
x[0]

# Let's index on the middle bracket (dim=1)
x[0][0]

# Let's index on the most inner bracket (last dimension)
x[0][0][0]

# you can also use ":" to select "all" of a target dimension
x[:,0]

# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1,1]

# Get index 0 of 0th and 1st dimension and all values of wnd dimension
x[0,0,:]

# Index on x to return 9
x[0,2,2]
# Index on x to return 3.6.9
x[:,:,2]

"""## Pytorch tensors & Numpy

NumPy is a popular scientific python numerical computiong library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor ->'torch.from_numpy(ndarray)'
* Pytorch tensor -> NumPy-> torch.Tensor.numpy()
"""

#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) #warning when converting from numpy -> pytorch,pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

#change the value of array, what will this do to 'tensor'?
array = array+1
array, tensor

# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

numpy_tensor.dtype

# Change the tensor, what happens to 'numpy_tensor?
tensor =tensor +1
tensor, numpy_tensor

"""## Reproducbility (trying to take random out of random)

In short how a neural network learns:

'start with randon numbers -> tensor operations -> update random numbers to try and
make them better representations of the data -> again -> again -> again... '

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does id "flavour" the randomness.
"""

import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

# Let's make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 100
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(100)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

"""## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware +PyThorch working behind the scenes to make eveything hunky

### 1. Getting a GPU

1. Easiest - use Google Colab for a free GPU.(options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options
3. Use cloud computing - GCP,AWS,Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch +gpu drivers (CUDA) takes a little bit of setting up, to do this,refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/
"""

!nvidia-smi

"""2. Check for GPU access with PyTorch"""

#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

"""For PyTorch since it's capable of running compute on the GPU or CPU,it's best practice to setup device agnosic code: https://docs.pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU
"""

# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Count number of devices
torch.cuda.device_count()

"""## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations
"""

# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], )

# Tensor not on GPU
print(tensor,tensor.device)

# Move tensor to GPu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

"""### 4. Moving tensors back to the CPU"""

# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

# To fix the GPU tensor with MunPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

tensor_on_gpu

"""## Exercises & Extra-Curriculum
see exercise: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

9/8 1시간 54분까지 시청함

9/9 3:44:45
"""

